name: to check disl space

on:
  push :
    branches: ["main"]   
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check Disk Space
        run: df -h
      - name: check
        run: ls -lrth
      - name: to check space
        run: du -hm \ | sort -rn |  head -n 10
      - name: checkinf docker images
        run: docker images
